# Generated by Django 4.2.7 on 2023-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/images/profile_pictures/default.png', upload_to='users/images/profile_pictures/'),
        ),
    ]
