# Generated by Django 4.2.7 on 2023-11-17 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_password1_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que el usuario se registró.', verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Ingrese su dirección de correo electrónico.', max_length=25, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Ingrese su nombre.', max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta del usuario está activa.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso al panel de administración.', verbose_name='Personal de Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Ingrese su apellido.', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(help_text='Ingrese su contraseña.', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(help_text='Ingrese nuevamente su contraseña para confirmar.', max_length=128, verbose_name='Confirmar Contraseña'),
        ),
    ]
