# Generated by Django 4.2.7 on 2023-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_date_joined_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/images/profile_pictures/default.png', upload_to='images/profile_pictures/'),
        ),
    ]
