# Generated by Django 4.2.7 on 2023-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile_pictures/default.png', upload_to='images/profile_pictures/'),
        ),
    ]
