version: '3.12'

services:
  web:
    build: .
    volumes:
      - .:/taskmaster
    ports:
      - "8000:8000"
    env_file:
      - .env 
    image: app:taskmaster
    container_name: taskmaster_container
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}