# Generated by Django 4.2.5 on 2023-10-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0012_alter_priority_options_alter_taskmetadata_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmetadata',
            name='priority',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo_task.priority'),
        ),
    ]
