# Generated by Django 4.2.5 on 2023-10-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0016_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
