# Generated by Django 4.2.5 on 2023-09-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0004_priority_alter_taskmetadata_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
