# Generated by Django 4.2.5 on 2023-10-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0013_alter_taskmetadata_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
