# Generated by Django 4.2.7 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0026_alter_label_options_alter_priority_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmetadata',
            options={'verbose_name': 'Metadata de Tarea', 'verbose_name_plural': 'Metadata de Tareas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(help_text='Ingrese la fecha de vencimiento, utilice este formato dd/mm/aaaa.', verbose_name='Fecha de Vencimiento'),
        ),
    ]
